---
title: "Module 1 Empirical Exercise"
author: "Econ 771: Health Economics II"
date: "Due: Friday, September 18"
output: 
  bookdown::html_document2:
    toc: TRUE
    toc_float: TRUE
    theme: darkly
    number_sections: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview
In this assignment, we're going to work through some applied issues related to causal inference in panel data, mainly focusing on difference-in-differences and event studies. These are the workhorses of modern applied empirical microeconomics (although not as much of a panacea as once perceived). 

To begin, please "accept" the assignment on our GitHub classroom page. This will initialize a GitHub repository where you can edit and ultimately craft your answers in your data management/econometrics software of choice.  

You will "turn in" your repository to me with your answers and all supporting documents. Please create a final document with your main answers and analyses in a PDF. Please also be sure to include in your repository all of your supporting code files. Practice writing good code and showing me only what I would need to recreate your results.


# Resources and data
The data for this assignment comes from two sources:

1. **Inpatient Prospective Payment System Final Rule Files**: The Centers for Medicare and Medicaid services publishes these data annually, and they contain some basic information about the types of patients admitted to hospitals in a given year. The data are available on our shared AWS AMI under the "IPPS" folder. They are also available for you to download directly from the [NBER IPPS Data](https://data.nber.org/data/cms-impact-file-hospital-inpatient-prospective-payment-system-ipps.html). You can get the data from CMS as well, but they no longer host the historic data so the NBER link is your best option for these exercises. Use these data to get information on hospital case mix and disproportionate share information.

2. **Provider of Services files**: These data are available from [NBER POS](https://data.nber.org/data/provider-of-services.html) as well as at [Adam Sacarny's GitHub repo](https://github.com/asacarny/provider-of-services). I've also made these data available on our shared AWS AMI in the "POS" folder. Use these data to get information on hospital ownership type.


# Questions
In your GitHub repository, please be sure to clearly address/answer the following questions.

1. Provide and discuss a table of simple summary statistics showing the mean, standard deviation, min, and max of the case mix index and disproportionate share across years. Show these statistics overall and separately by hospital ownership type.

2. Create a figure showing the average hospital disproportionate shares from 1986 to 2000.

3. Approximate the analysis from Dafny (2005) using the Case Mix Index as the outcome of interest. Did hospitals' CMI increase following the change to the DRG adjustments in 1988? Does the effect differ by ownership status?

4. Estimate an "event study" version of the DD model from part 3.