---
title: "Consumerism in health care"
subtitle: "<html><div style='float:left'></div><hr color='#EB811B' size=1px width=0px></html>"
author: Horwitz and Nichols (2009), Bayindir (2012)
date: Comments by Ian McCarthy | Econ 771 #"`r format(Sys.time(), '%d %B %Y')`"
header-includes: 
  - \usepackage{tikz}
  - \usepackage{amsmath}
  - \usepackage{pgf}
  - \usepackage[xcolor=pst]{pstricks}
  - \usepackage{pgfshade}
  - \usepackage{pdftools}
  - \usepackage{color}
  - \usepackage{colortbl}
  - \usepackage{xcolor}
output:
#  html_document: default (toggle on for "simplified" view)
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts, custom.css] 
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      beforeInit: "macros.js"
      navigation:
          touch: false
---

<!-- Adjust some CSS code for font size and maintain R code font size -->
<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 2em 1em 2em;    
}
.remark-code, .remark-inline-code { 
    font-size: 20px;
}
</style>


<!-- Set R options for how code chunks are displayed and load packages -->
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=3, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )

knitr::opts_hooks$set(fig.callout = function(options) {
  if(options$fig.callout) {
    options$echo = FALSE
  }
  options
})

```


# Table of contents

1. [Motivation](#motivation)

2. [Chernew et al. (2019)](#chernew)

3. [Ketcham et al. (2012)](#ketcham)

4. [Takeaways](#final)


<!-- New Section -->
---
class: inverse, center, middle
name: motivation

# Motivation

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=1055px></html>

---
# Motivation

Huge movement toward "consumerism" in health care

- show graph of cost sharing over time


---
# Motivation

- Do people shop for health care? (context of MRI scans)
- Do people learn what's best for them? (context of Medicare Part D)


<!-- New Section -->
---
class: inverse, center, middle
name: chernew

# Chernew et al. (2019)

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=1055px></html>


---
# Main empirical question

Are health care services "shoppable"? Study this in the context of MRIs where quality is homogeneous.

<br>
--
- If so, more consumerism might be OK
- If not, need other tools for now


---
# Contribution

- Policy on "consumerism"
- Physician agency and role of physician referrals


---
# Preview of findings

- Patients pass 6 lower-priced facilities en route to selected facility
- 50% potential drop if people went to cheapest facility

- figure 1 of paper


---
# Main data:

- Private insurance claims in 2013 (single insurer, but a large one)
- SK&A data on physician practices
- Limit to orthopedics
- Data on who used a shopping tool provided by the insurer ($<$1%)

---
# Empirical analysis:

- Mainly descriptive statistics
- Calculate counterfactual prices using the mean price of each location


---
# Findings

- Markets have nearly 2x range from 20th to 80th price percentile
- $468.53 mean savings per case (55% drop) within 1 hour drive
- 36% drop without change in driving distance
- $<$ 1% shop
- Referring physician controls 50% of the savings


---
class: inverse, center, middle
name: ketcham

# Ketcham et al. (2012)

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=1055px></html>

---
# Motivation

- Lots of perceived "poor" decisions in Part D choice
- What's the source of these poor decisions? 

<br>
--
- If people just *can't* make a good decision, then we need some intervention
- If people are larning, then perhaps less need for intervention

---
# Main empirical question

Do people improve the match quality of their Part D insurance choice over time?

---
# Contribution

- Large literature on poor decision making in insurance, especially Part D 
- Many interventions designed based off of this literature:<br>
  - decision assistance
  - default plan assignment
  - informational letters
  - restrictions on choice size

<br>  
--
**NOT** limited to insurance...credit cards, mortgages, other financial instruments

---
# Preview of findings

---
# Data
